name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
  coverage:
    needs: [ build ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: 7dc5fd15c3c44b3e5540eff8ecfa4b6ebeae19c6f439b285daf663462ae52c5b
      with:
        coverageCommand: npm run coverage
        coverageLocations:
          "${{github.workspace}}/coverage/lcov.info:lcov"